StartupEvents.registry('item', event => {

	event.create('gud_toolkit:ethereal_fabric').maxStackSize(64).texture('gud_toolkit:item/ethereal_fabric').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:erratic_stone').maxStackSize(64).texture('gud_toolkit:item/erratic_stone').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:etched_iron').maxStackSize(64).texture('gud_toolkit:item/etched_iron').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:great_arcane_ingot').maxStackSize(64).texture('gud_toolkit:item/great_arcane_ingot').rarity('rare').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:purgatory_forge').maxStackSize(64).texture('gud_toolkit:item/purgatory_forge').rarity('epic').fireResistant(true).group("kubejs.gud_toolkit")
	event.create('gud_toolkit:mana_developer').maxStackSize(64).texture('gud_toolkit:item/mana_developer').glow(true).group("kubejs.gud_toolkit")
	event.create('gud_toolkit:unclean_blood').maxStackSize(64).burnTime(200000).texture('gud_toolkit:item/unclean_blood').rarity('uncommon').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:hateful_soul').maxStackSize(1).texture('gud_toolkit:item/hateful_soul').rarity('epic').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:cursed_blade').maxStackSize(1).texture('gud_toolkit:item/cursed_blade').rarity('epic').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:index_blade').maxStackSize(1).texture('gud_toolkit:item/index_blade').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:chainsaw_blade').maxStackSize(1).texture('gud_toolkit:item/chainsaw_blade').group("kubejs.gud_toolkit")
	event.create('gud_toolkit:processing_index_blade').texture('gud_toolkit:item/processing_index_blade')
	event.create('gud_toolkit:processing_chainsaw_blade').texture('gud_toolkit:item/processing_chainsaw_blade')
	event.create('gud_toolkit:processing_cast_burner').texture('gud_toolkit:item/processing_cast_burner')

	event.create('gud_toolkit:vanity_crown').group("kubejs.gud_toolkit").rarity('rare')
	.texture('gud_toolkit:item/vanity_crown')
	.maxStackSize(1)
	.tag('curios:head')
	.attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
	.canEquip(() => true))

	event.create('gud_toolkit:etched_charm').group("kubejs.gud_toolkit")
	.texture('gud_toolkit:item/etched_charm')
	.maxStackSize(1)
	.tag('curios:necklace')
	.tag('curios:trinkets')
	.attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
	.canEquip(() => true))

	event.create('gud_toolkit:ethereal_cape').group("kubejs.gud_toolkit")
	.texture('gud_toolkit:item/ethereal_cape')
	.maxStackSize(1)
	.tag('curios:body')
	.attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
	.canEquip(() => true))

	event.create('gud_toolkit:sharp_shadow').group("kubejs.gud_toolkit")
	.texture('gud_toolkit:item/sharp_shadow')
	.maxStackSize(1)
	.tag('curios:body')
	.attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
	.canEquip(() => true))

	event.create('gud_toolkit:dead_luck').group("kubejs.gud_toolkit").rarity('epic')
	.texture('gud_toolkit:item/dead_luck')
	.maxStackSize(1)
	.tag('curios:trinkets')
	.attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
	.canEquip(() => true))

	event.create('gud_toolkit:purgatory_ring').group("kubejs.gud_toolkit").rarity('epic').fireResistant(true)
	.texture('gud_toolkit:item/purgatory_ring')
	.maxStackSize(1)
	.tag('curios:ring')
	.attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
	.canEquip(() => true))

	event.create('gud_toolkit:recitative', "irons_spells_js:staff").group("kubejs.gud_toolkit")
	.attackDamageBaseline(11)
	.speedBaseline(-1)
	.speed(6)
	.addAdditionalAttribute('irons_spellbooks:max_mana', 'RecitativeStaff', 350, 'addition')
	.addAdditionalAttribute('irons_spellbooks:spell_power', 'RecitativeStaff', 0.1, 'multiply_base')
	.addAdditionalAttribute('irons_spellbooks:mana_regen', 'RecitativeStaff', 0.3, 'multiply_total')
	.addAdditionalAttribute('irons_spellbooks:cooldown_reduction', 'RecitativeStaff', 0.2, 'multiply_total')
	.addAdditionalAttribute('irons_spellbooks:cast_time_reduction', 'RecitativeStaff', 0.2, 'multiply_total')
	.rarity('rare')

	event.create("gud_toolkit:aria", "irons_spells_js:magic_sword").group("kubejs.gud_toolkit")
	.addAdditionalAttribute('irons_spellbooks:cooldown_reduction', 'Aria', 0.3, 'multiply_total')
	.addAdditionalAttribute('irons_spellbooks:cast_time_reduction', 'Aria', 0.3, 'multiply_total')
	.addDefaultSpell('irons_spellbooks:eldritch_blast', 5)
	.rarity('rare')

	event.create('gud_toolkit:cast_burner', 'irons_spells_js:spellbook')
	.tag('curios:trinkets')
	.setMaxSpellSlots(1)
	.addDefaultSpell('irons_spellbooks:counterspell', 1)
	.addDefaultAttribute('additional_attributes:keep_scroll', 'CastBurner', 1, 'addition')
	.addDefaultAttribute('irons_spellbooks:spell_power', 'CastBurner', -0.3, 'multiply_total')
	.addDefaultAttribute('irons_spellbooks:cast_time_reduction', 'CastBurner', -0.15, 'multiply_total')

	event.create('gud_toolkit:outer_chat', 'irons_spells_js:spellbook')
	.setMaxSpellSlots(15)
	.addDefaultAttribute('generic.max_health', 'OuterChat', -0.5, 'multiply_total')
	.addDefaultAttribute('irons_spellbooks:spell_power', 'OuterChat', 0.3, 'multiply_total')
	.addDefaultAttribute('irons_spellbooks:cast_time_reduction', 'OuterChat', 0.3, 'multiply_total')
	.addDefaultAttribute('irons_spellbooks:cooldown_reduction', 'OuterChat', 0.3, 'multiply_total')

	event.create('gud_toolkit:creative_spell_book', 'irons_spells_js:spellbook')
	.setMaxSpellSlots(15)
	.addDefaultAttribute('additional_attributes:keep_scroll', 'CreativeSpellBook', 1, 'addition')
	.addDefaultAttribute('irons_spellbooks:max_mana', 'CreativeSpellBook', 1000000, 'addition')
	.addDefaultAttribute('irons_spellbooks:spell_power', 'CreativeSpellBook', 10, 'multiply_total')
	.addDefaultAttribute('irons_spellbooks:cast_time_reduction', 'CreativeSpellBook', 1000, 'multiply_total')
	.addDefaultAttribute('irons_spellbooks:cooldown_reduction', 'CreativeSpellBook', 1000, 'multiply_total')

})